
/*
 * 
 */

package https.sassgateway_adp_com.vendorxml.vendorservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue May 04 10:38:59 MDT 2010
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "VendorServiceImplService", 
                  wsdlLocation = "http://exfit01.select.adp.com/vendorxml/VendorService/v1?wsdl",
                  targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1") 
public class VendorServiceFitImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("https://sassgateway.adp.com/vendorxml/VendorService/v1", "VendorServiceImplService");
    public final static QName VendorServiceFitImplPort = new QName("https://sassgateway.adp.com/vendorxml/VendorService/v1", "VendorServiceImplPort");
  	 public final static String wsdl = "SASSVendorServiceV1.wsdl";
    static {
        URL url = null;
      	url = VendorServiceFitImplService.class.getClassLoader().getResource(wsdl);
    		WSDL_LOCATION = url;
      	
        if (url==null){  
        	System.err.println("Can not initialize the default wsdl" +wsdl);
        }
    }

    public VendorServiceFitImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VendorServiceFitImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VendorServiceFitImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns VendorServiceFit
     */
    @WebEndpoint(name = "VendorServiceImplPort")
    public VendorServiceFit getVendorServiceFitImplPort() {
        return super.getPort(VendorServiceFitImplPort, VendorServiceFit.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VendorServiceFit
     */
    @WebEndpoint(name = "VendorServiceImplPort")
    public VendorServiceFit getVendorServiceFitImplPort(WebServiceFeature... features) {
        return super.getPort(VendorServiceFitImplPort, VendorServiceFit.class, features);
    }

}
