package com.adp.base;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import https.sassgateway_adp_com.vendorxml.vendorservice.v1.GVXException_Exception;
import https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorAcknowledgement;
import https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorGetWork;

/**
 * This class was generated by Apache CXF 2.2.6 Thu Mar 04 10:13:03 MST 2010
 * Generated source version: 2.2.6
 * 
 */

public  class VendorServiceSuperGetWork extends SuperVendorServiceClient {



	protected void runTest(String hostLocation) throws Exception {
		
		MessageVendorGetWork _getwork_getworkRequest = new MessageVendorGetWork();
		if(hostLocation.equals("DIT"))
		{
		_getwork_getworkRequest.setUserId(p.getProperty("dit_userid"));
		System.out.println("Invoking getwork (DIT)...");
		}
		else if(hostLocation.equals("FIT"))
		{
			_getwork_getworkRequest.setUserId(p.getProperty("fit_userid"));
			System.out.println("Invoking getwork (FIT)...");
		}
		else if(hostLocation.equals("IAT"))
		{
			_getwork_getworkRequest.setUserId(p.getProperty("iat_userid"));
			System.out.println("Invoking getwork (IAT)...");
		}
		else if(hostLocation.equals("PROD"))
		{
			_getwork_getworkRequest.setUserId(p.getProperty("prod_userid"));
			System.out.println("Invoking getwork (PROD)...");
		}
		_getwork_getworkRequest.setExistingWork(p.getProperty("getworkExist"));

		try {
			
			MessageVendorAcknowledgement _getwork__return = null;
			if(hostLocation.equals("DIT")){
				_getwork__return =portDit
					.getWork(_getwork_getworkRequest);
			}
			else if (hostLocation.equals("FIT")){
				_getwork__return =portFit.getWork(_getwork_getworkRequest);
			}
			
			else if (hostLocation.equals("IAT")){
				_getwork__return =portiAT.getWork(_getwork_getworkRequest);
			}
			else if (hostLocation.equals("PROD")){
				_getwork__return =portProd.getWork(_getwork_getworkRequest);
			}
			
			
			System.out.println("getWork.result=" + _getwork__return);
			if (_getwork__return.getVendorWorks().size() > 0) {
				for (int i = 0; i < _getwork__return.getVendorWorks().size(); i++) {

					System.out.println("Batch Date : "
							+ _getwork__return.getVendorWorks().get(i)
									.getBatchDate());
					System.out.println("Reference String: "
							+ _getwork__return.getVendorWorks().get(i)
									.getSassRefString());
					System.out.println("Address Line 1: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonAddress().getAddressLine1());
					System.out.println("Address Line 2: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonAddress().getAddressLine2());
					System.out.println("City: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonAddress().getCity());
					System.out.println("State: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonAddress().getState());
					System.out.println("Zip Code: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonAddress().getZipCode());

					System.out.println("Date Of Birth: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getDateOfBirth());
					System.out.println("Eye Color: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getEyeColor());
					System.out.println("First Name: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getFirstName());
					System.out.println("Last Name: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getLastName());
					System.out.println("Middle Name: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getMiddleName());

					System.out.println("Gender: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getGender());
					System.out.println("Hair Color: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getHairColor());
					System.out.println("Height: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getHeight());
					System.out.println("Scars: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getScars());
					System.out.println("Race: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getRace());
					System.out.println("SSN: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getSsn());
					System.out.println("Weight: "
							+ _getwork__return.getVendorWorks().get(i)
									.getPersonIdentifier().getWeight());
					System.out
							.println("=================================================================================");

				}
			} else {
				System.out.println("No Record Found");
			}
		} catch (GVXException_Exception e) {
			System.out
					.println("Expected exception: GVXException has occurred.");
			System.out.println(e.toString());
		}

		System.exit(0);
	}
}
