package com.adp.prodclient;





/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import https.sassgateway_adp_com.vendorxml.vendorservice.v1.GVXException_Exception;
import https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorAcknowledgement;
import https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorPing;
import https.sassgateway_adp_com.vendorxml.vendorservice.v1.VendorServiceFitImplService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import com.adp.base.SuperVendorServiceClient;


/**
 * This class was generated by Apache CXF 2.2.6 Thu Mar 04 10:13:03 MST 2010
 * Generated source version: 2.2.6
 * 
 */

public final class VendorServicePRODPingClient extends SuperVendorServiceClient {


	public static void main(String args[]) throws Exception {
		URL wsdlURL = VendorServiceFitImplService.WSDL_LOCATION;
		if (args.length > 0) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}
		VendorServicePRODPingClient client = new VendorServicePRODPingClient();
		client.setService(wsdlURL,"PROD");
		client.runTest();
	}

	private void runTest() {
		System.out.println("Invoking ping(PROD)...");

		MessageVendorPing _ping_pingRequest = new MessageVendorPing();
		_ping_pingRequest.setUserId(p.getProperty("prod_userid"));

		try {
			MessageVendorAcknowledgement _ping__return = portDit
					.ping(_ping_pingRequest);
			System.out.println("ping.result=" + _ping__return);
			System.out.println("The status: "+_ping__return.getOverallStatus());
		} catch (GVXException_Exception e) {
			System.out
					.println("Expected exception: GVXException has occurred.");
			System.out.println(e.toString());
		}

		System.exit(0);
	}
}
