package https.sassgateway_adp_com.vendorxml.vendorservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue May 04 10:38:59 MDT 2010
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", name = "VendorServiceIAT")
@XmlSeeAlso({ObjectFactory.class})
public interface VendorServiceIAT {

    @WebResult(name = "acknowledgement", targetNamespace = "")
    @RequestWrapper(localName = "getWork", targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", className = "https.sassgateway_adp_com.vendorxml.vendorservice.v1.GetWork")
    @WebMethod
    @ResponseWrapper(localName = "getWorkResponse", targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", className = "https.sassgateway_adp_com.vendorxml.vendorservice.v1.GetWorkResponse")
    public https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorAcknowledgement getWork(
        @WebParam(name = "getWorkRequest", targetNamespace = "")
        https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorGetWork getWorkRequest
    ) throws GVXException_Exception;

    @WebResult(name = "acknowledgement", targetNamespace = "")
    @RequestWrapper(localName = "fulfillCriminalHistory", targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", className = "https.sassgateway_adp_com.vendorxml.vendorservice.v1.FulfillCriminalHistory")
    @WebMethod
    @ResponseWrapper(localName = "fulfillCriminalHistoryResponse", targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", className = "https.sassgateway_adp_com.vendorxml.vendorservice.v1.FulfillCriminalHistoryResponse")
    public https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorAcknowledgement fulfillCriminalHistory(
        @WebParam(name = "fulfillCriminalHistoryRequest", targetNamespace = "")
        https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorFulfillWork fulfillCriminalHistoryRequest
    ) throws GVXException_Exception;

    @WebResult(name = "acknowledgement", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", className = "https.sassgateway_adp_com.vendorxml.vendorservice.v1.Ping")
    @WebMethod
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "https://sassgateway.adp.com/vendorxml/VendorService/v1", className = "https.sassgateway_adp_com.vendorxml.vendorservice.v1.PingResponse")
    public https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorAcknowledgement ping(
        @WebParam(name = "pingRequest", targetNamespace = "")
        https.sassgateway_adp_com.vendorxml.vendorservice.v1.MessageVendorPing pingRequest
    ) throws GVXException_Exception;
}
